name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Git SHA commit to be deployed"
        required: true

env:
  SERVICE_NAME: raspberry-aws-iot
  AWS_ACCOUNT: 568480506324
  AWS_REGION: eu-west-1
  PYTHON_VERSION: 3.8
  S3_BUCKET: mattiot-website-prod


jobs:
  deploy-webapp-prod:
    name: Deploy to WebApp to prod
    runs-on: ubuntu-latest
    needs: package-web-app
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ github.event.inputs.gitRef }}"
      - name: Configure Prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ci-deployer-role-prod
          role-duration-seconds: 1200
          role-session-name: GithubDeployProd
      - name: Deploy Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{env.SERVICE_NAME}}-prod
          template: webapp/template.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            Env=prod,
            ServiceName=${{env.SERVICE_NAME}},
            Account=${{env.AWS_ACCOUNT}},
            Region=${{env.AWS_REGION}},
            BucketName=${{env.S3_BUCKET}},
            ImageTag=${{github.event.inputs.gitRef}}


  deploy-s3-website:
    name: Deploy S3 website to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ci-deployer-role-prod
          role-duration-seconds: 1200
          role-session-name: GithubDeployProd
      - name: Choose config file
        run: |
          rm ./webapp/static/js/config.dev.js
          mv ./webapp/static/js/config.prod.js ./webapp/static/js/config.js
      - name: Deploy
        run: |
          aws s3 sync ./webapp/static s3://${{ env.S3_BUCKET }} \
            --delete \
            --cache-control 'public, must-revalidate, proxy-revalidate, max-age=0'